#
# Before using this .gitlab-ci.yml:
#
# - This example uses the latest Docker image, but you might want to use the
#   exact version to avoid any broken pipelines.
#   All available Hugo versions are listed under https://gitlab.com/pages/hugo/container_registry.
# - Read about the difference between hugo and hugo_extended
#   https://gitlab.com/pages/hugo/-/blob/main/README.md#hugo-vs-hugo_extended.
# - To change the theme, see
#   https://gitlab.com/pages/hugo/-/blob/main/README.md#use-a-custom-theme.
#
image: ubuntu:latest

# Set this if you intend to use Git submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production
  HUGO_VERSION: 0.108.0

default:
  before_script:
    - apt -y update
    - apt -y install snapd wget sudo git curl
    - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
    - apt -y install nodejs
    - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb && sudo dpkg -i /tmp/hugo.deb
    - wget -O /tmp/d.tar.gz https://github.com/sass/dart-sass-embedded/releases/download/1.62.0/sass_embedded-1.62.0-linux-x64.tar.gz && tar -xzvf /tmp/d.tar.gz && sudo cp sass_embedded/dart-sass-embedded /usr/bin 
    - git submodule update --init --recursive
    - "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

pages:
  script:
    - hugo --minify --baseURL "https://iampaigeat.gitlab.io/paigeadelethompson/"
  artifacts:
    paths:
      - public
