baseurl      = "/"
languageCode = "en-us"
theme        = "c0ns0l3"
paginate     = 8

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  contentTypeName      = "posts"
  showMenuItems        = 8
  showLanguageSelector = false
  autoCover            = true
  showLastUpdated      = true
  OGImageWidth         = 499
  OGImageHeight        = 627
  toc                  = true
  custom_css           = ["/formio/formio.full.min.css", "/formio/formio.builder.min.css"]
  custom_js            = ["/formio/formio.full.min.js"]
  googleAnalyticsID    = "G-YG2468NJFV"

[params.twitter]
  creator = "IAmPaigeAT"
  site    = "IAmPaigeAT"

[languages]
  [languages.en]
    languageName           = "English"
    title                  = "paige.bio"
    subtitle               = "Paige's home page"
    owner                  = "Paige Thompson"
    keywords               = "Computers, Programming, Paige Thompson, Seattle, Art"
    copyright              = "2023"
    menuMore               = "Show more"
    readMore               = "Read more"
    readOtherPosts         = "Read other posts"
    newerPosts             = "Newer posts"
    olderPosts             = "Older posts"
    missingContentMessage  = "Page not found..."
    missingBackButtonLabel = "Back to main page"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "About"
        name       = "Resume"
        url        = "/resume"

      [[languages.en.menu.main]]
        identifier = "showcase"
        name       = "Posts"
        url        = "/"

      [[languages.en.menu.main]]
        identifier = "bookmarks"
        name       = "Bookmarks"
        url        = "/bookmarks"

      [[languages.en.menu.main]]
        identifier = "PGP"
        name       = "PGP"
        url        = "/pgp"

      [[languages.en.menu.main]]
        identifier = "NFTablesPresentation"
        name       = "NFTables Presentation"
        url        = "/nftables_presentation"
        
[module]
  [[module.mounts]]
    source = "node_modules/emulators-ui/dist"
    target = "static/emulators-ui"

  [[module.mounts]]
    source = "node_modules/emulators/dist"
    target = "static/emulators"

  [[module.mounts]]
    source = "static/jsdos"
    target = "static/jsdos"

  [[module.mounts]]
    source = "static/img"
    target = "static/img"
  
  [[module.mounts]]
    source = "node_modules/webamp/built"
    target = "static/webamp"

  [[module.mounts]]
    source = "static/webamp_theme"
    target = "static/webamp_theme"

  [[module.mounts]]
    source = "node_modules/formiojs/dist/"
    target = "static/formio"

  [[module.mounts]]
    source = "node_modules/traviso.js/dist/browser/"    
    target = "static/traviso"

  [[module.mounts]]
    source = "node_modules/pixi.js/dist/"
    target = "static/pixi"

  [[module.mounts]]
    source = "static/traviso_example"
    target = "static/traviso_example"
