baseurl      = "/"
languageCode = "en-us"
theme        = "c0ns0l3"
paginate     = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  contentTypeName      = "posts"
  showMenuItems        = 3
  showLanguageSelector = false
  autoCover            = true
  showLastUpdated      = true
  OGImageWidth         = 499
  OGImageHeight        = 627


[params.twitter]
  creator = "IAmPaigeAT"
  site    = "IAmPaigeAT"

[languages]
  [languages.en]
    languageName           = "English"
    title                  = "paige.bio"
    subtitle               = "Personal home page"
    owner                  = "Paige Thompson"
    keywords               = "Computers, Programming, Paige Thompson"
    copyright              = "2023"
    menuMore               = "Show more"
    readMore               = "Read more"
    readOtherPosts         = "Read other posts"
    newerPosts             = "Newer posts"
    olderPosts             = "Older posts"
    missingContentMessage  = "Page not found..."
    missingBackButtonLabel = "Back to main page"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name       = "Resume"
        url        = "/resume"

      [[languages.en.menu.main]]
        identifier = "showcase"
        name       = "Posts"
        url        = "/"

      [[languages.en.menu.main]]
        identifier = "bookmarks"
        name       = "Bookmarks"
        url        = "/bookmarks"

      [[languages.en.menu.main]]
        identifier = "PGP"
        name       = "PGP"
        url        = "/pgp"

      [[languages.en.menu.main]]
        identifier = "NFTablesPresentation"
        name       = "NFTables Presentation"
        url        = "/nftables_presentation"

[module]
  [[module.mounts]]
    source = "node_modules/stockfish/src/stockfish.js"
    target = "static/stockfish/stockfish.js"
  [[module.mounts]]
    source = "node_modules/emulators-ui/dist"
    target = "static/emulators-ui"
  [[module.mounts]]
    source = "node_modules/emulators/dist"
    target = "static/emulators"
  [[module.mounts]]
    source = "static/jsdos"
    target = "static/jsdos"
[[module.mounts]]
    source = "static/img"
    target = "static/img"
